version: "3.8"
services:
  #  tokkyokun_tweet_app:
  #    image: tokkyokun/tweet_app:v1.0.0
  #    container_name: tokkyokun_tweet_app
  #    hostname: tokkyokun_tweet_app
  #    logging:
  #      driver: json-file
  #      options:
  #        max-file: "1"
  #        max-size: 5m
  tokkyokun_db:
    image: postgres:14.5
    container_name: tokkyokun_db
    hostname: tokkyokun_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 5m
    ports:
      - "5435:5432"
    volumes:
      - ./volume/tmp:/tmp