spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5435/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    clean-on-validation-error: true
tokkyokun:
  patentdata:
    basepath: ./
