spring:
  application:
    name: tokkyokun #app name
  profiles:
    active: ${PROFILE:local} #profile
  main:
    web-application-type: none
  flyway:
    clean-on-validation-error: false
jplatpat:
  username: ${J_PLAT_PAT_USERNAME:username}
  password: ${J_PLAT_PAT_PASSWORD:password}
